name: caresync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.11
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  firebase_core: ^3.7.0
  cloud_firestore: ^5.5.0
  animated_bottom_navigation_bar: ^1.3.3
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  shared_preferences: ^2.3.3
  animate_do: ^3.3.4
  firebase_database: ^11.1.6
  firebase_storage: ^12.3.6
  file_picker: ^8.1.4
  pie_chart: ^5.4.0
  
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/png/MedicalStores/
    - assets/png/Categories/
    - assets/png/Category1/
    - assets/png/Category2/
    - assets/png/Category3/
    - assets/png/Category4/
    - assets/png/Category5/
    - assets/png/Category6/
    - assets/png/Category7/
    - assets/png/Category8/
    - assets/png/Category9/
    - assets/png/Category10/
    - assets/jpg/MedicalStoreCaraoiusal/
    - assets/jpg/CategoryCaraiousal/
    - assets/jpg/Categories/
    - assets/jpg/HomeScreen/
    - assets/jpg/
    - assets/jpeg/
    - assets/svg/doctor.svg
    - assets/png/AmulanceCarasiousal/
    - assets/jpg/ChatApp/
    - assets/jpg/Ayurveda/
    - assets/jpg/DoctorSide/
    - assets/png/DoctorSide/
    - assets/png/images/
    - assets/svg/record.svg
    - assets/jpg/images/
    - assets/jpg/carousel_jpg/
    - assets/svg/specialisation/
    - assets/svg/
    - assets/png/drHome.png
